name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup uv
        uses: astral-sh/setup-uv@6.0.1
        with:
          python-version: ${{ matrix.python }}
          activate-environment: true

      - name: Install dependencies
        run: uv sync --group dev --group test

      - name: Run tests
        run: nox -s pytest

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup uv
        uses: astral-sh/setup-uv@6.0.1
        with:
          python-version: "3.10"
          activate-environment: true

      - name: Install dependencies
        run: uv sync --group dev --group format
      
      - name: Run format
        run: nox -s format-check

  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup uv
        uses: astral-sh/setup-uv@6.0.1
        with:
          python-version: "3.10"
          activate-environment: true

      - name: Install dependencies
        run: uv sync --group dev --group doc
      
      - name: Run format
        run: nox -s docs
